package com.example.freelanceP.creator;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.*;

@Entity
@Table
public class Creator {
    //mapped this student class in our database
    @Id
    @SequenceGenerator(
            name="creator_sequence",
            sequenceName = "creator_sequence",
            allocationSize = 1
    )
    @GeneratedValue(
            strategy = GenerationType.SEQUENCE,
            generator = "creator_sequence"
    )

    private Long creID;
    private String name;
    private String phoneNumber;
    private String userName;
    private String email;
    private LocalDate Dob;
    //anotate with transient to auto calculate age from date of birth
    //no need to have age in our database it self calculatory
    //will remove age from all constructors
    @Transient
    private Integer age;
    private String password;

    public Creator() { //added cause of an error
    }

    public Creator(long l, String oliver, String s, String oli, String s1, LocalDate of) {
    }
 //contstructor with all variables

    public Creator(Long creID, String name, String phoneNumber, String userName, String email, LocalDate dob,  /*removed age*/ String password) {
        this.creID = creID;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.userName = userName;
        this.email = email;
        Dob = dob;
        //removed age
        this.password = password;
    }


    //contstructor with all variables except ID
    //id will be generated by the database
    public Creator(String name, String phoneNumber, String userName, String email, LocalDate dob, /*removed age*/ String password) {
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.userName = userName;
        this.email = email;
        Dob = dob;
        //removed age
        this.password = password;
    }

    //getters and setteres

    public Long getCreID() {
        return creID;
    }

    public void setCreID(Long creID) {
        this.creID = creID;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public LocalDate getDob() {
        return Dob;
    }

    public void setDob(LocalDate dob) {
        Dob = dob;
    }

    public Integer getAge() {
      //  return age;
        //generating age based on dateOfBirth
        return Period.between(this.Dob,LocalDate.now()).getYears();
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
 // a to string

    @Override
    public String toString() {
        return "Creator{" +
                "creID=" + creID +
                ", name='" + name + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", userName='" + userName + '\'' +
                ", email='" + email + '\'' +
                ", Dob=" + Dob +
                ", age=" + age +
                '}';
    }
}
